It testing
IBM-Blockchain/ibp-go-sdk pull request #11
Opened 2020-12-14 21:06 UTC by chrissharp80

2020-12-14 21:39 UTC, mrshah-at-ibm requested changes

2020-12-14 21:39 UTC, mrshah-at-ibm commented on integration_test/integration_functions_lib.go
> +	Logger    *log.Logger
Can we add a default logger if a logger is not set?

2020-12-14 21:39 UTC, mrshah-at-ibm commented on integration_test/integration_functions_lib.go
> +	// decode the base64 string in the CA's MSP
The comment about what the function does should be put above the function.
Ref: https://golang.org/src/go/doc/example.go

2020-12-14 21:39 UTC, mrshah-at-ibm commented on integration_test/integration_functions_lib.go
> +	for !time.Now().After(deadline) { // make sure we're not past our five minute deadline
looks like we are setting up a 10 minutes deadline

2020-12-14 21:39 UTC, mrshah-at-ibm commented on integration_test/integration_functions_lib.go
> +		resp, err := client.Get(apiUrl + "/cainfo")
is this loop going to run with no sleep? we should look at using Poll or ticker.

2020-12-14 21:39 UTC, mrshah-at-ibm commented on integration_test/integration_test.go
> +	service, err = createAService(setupInfo)
we are creating a blockchain "service instance". We can update the comment.

2020-12-15 01:07 UTC, chrissharp80 commented on integration_test/integration_functions_lib.go
> +	Logger    *log.Logger
done

2020-12-15 01:10 UTC, chrissharp80 commented on integration_test/integration_functions_lib.go
> +	// decode the base64 string in the CA's MSP
This comment is about that function call to decode the string. It's mainly there to quickly see where the base64 string came from. The function returns it in decoded form. I see your point though, given the name of the function. Moving the comment now.

2020-12-15 01:11 UTC, chrissharp80 commented on integration_test/integration_functions_lib.go
> +	for !time.Now().After(deadline) { // make sure we're not past our five minute deadline
fixed

2020-12-15 01:18 UTC, chrissharp80 commented on integration_test/integration_functions_lib.go
> +		resp, err := client.Get(apiUrl + "/cainfo")
I put it to sleep for 2 seconds each time through use `time.sleep()`.

2020-12-15 01:19 UTC, chrissharp80 commented on integration_test/integration_test.go
> +	service, err = createAService(setupInfo)
done

2020-12-15 18:09 UTC, dshuffma-ibm requested changes
I'd like this integrated with github actions and see theses tests pass before merging

2020-12-17 13:46 UTC, chrissharp80 commented
@mrshah-at-ibm this PR would not work with Github Actions from a fork because the env variables are not exposed to a fork, even if it has the same ones set. As a result, I created a branch from the main repo and pushed my code there. I would like to have this PR closed.

2020-12-17 13:53 UTC, mrshah-at-ibm approved these changes

2020-12-17 13:53 UTC, mrshah-at-ibm commented on integration_test/integration_functions_lib.go
> +	// convert the tls cert from the newly created CA into a format that can be used to create a PEM file
The comment for the function should go above the Function definition.

2020-12-17 13:53 UTC, mrshah-at-ibm commented on integration_test/integration_functions_lib.go
> +	// create a client config and enable it with TLS (using the tls cert from the CA's MSP)
comment before function definition

2020-12-17 13:53 UTC, mrshah-at-ibm commented on integration_test/integration_functions_lib.go
> +	// use the client to enroll the CA
comment before function definition

2020-12-17 13:53 UTC, mrshah-at-ibm commented on integration_test/integration_functions_lib.go
> +		resp, err := client.Get(apiUrl + "/cainfo")
cool. I think Poll or ticker would be a better implementation. But that should not block this.

2020-12-17 14:42 UTC, dshuffma-ibm commented
closing, dup of https://github.com/IBM-Blockchain/ibp-go-sdk/pull/12

2020-12-17 14:42 UTC, closed without merging