basic integration test with github actions
IBM-Blockchain/ibp-go-sdk pull request #12
Opened 2020-12-16 21:13 UTC by chrissharp80

2020-12-17 14:04 UTC, mrshah-at-ibm requested changes

2020-12-17 14:04 UTC, mrshah-at-ibm commented on integration_test/integration_functions_lib.go
> +	for !time.Now().After(deadline) { // make sure we're not past our deadline
I feel poll or ticker would be a better implementation. But, this one works as well. This won't block merging of the PR.

2020-12-17 14:04 UTC, mrshah-at-ibm commented on integration_test/integration_functions_lib.go
> +		removeIdentity(name, enrollResp) // dsh comment out this line to run it without it ever removing anything
Is this comment required?

2020-12-17 14:07 UTC, chrissharp80 commented on .gitignore
> +# lcs
They are for anyone who runs it locally. This particular one is likely unnecessary as the pem is useless and even then should get cleaned up at the end of the test. I see no harm in this line, though, in case something goes wrong.

2021-01-07 18:02 UTC, dshuffma-ibm approved these changes
I went through the action build, it looks good. we could merge what you have and get the rest of the apis later. though you should fix up mihir's comments first too.

2021-01-07 18:15 UTC, chrissharp80 commented on integration_test/integration_functions_lib.go
> +		removeIdentity(name, enrollResp) // dsh comment out this line to run it without it ever removing anything
fixed

2021-01-07 18:15 UTC, chrissharp80 commented on integration_test/integration_functions_lib.go
> +	// use the client to enroll the CA
fixed

2021-01-07 18:15 UTC, chrissharp80 commented on integration_test/integration_functions_lib.go
> +	// create a client config and enable it with TLS (using the tls cert from the CA's MSP)
fixed

2021-01-07 18:16 UTC, chrissharp80 commented on integration_test/integration_functions_lib.go
> +	// convert the tls cert from the newly created CA into a format that can be used to create a PEM file
fixed

2021-01-07 18:18 UTC, mrshah-at-ibm approved these changes

2021-01-07 18:21 UTC, merged